### ISSUE TITLE
running Norgal

### ISSUE THREAD

**Issue by rjsorr** [kosaidtu/norgal#1]
Hi, 
hope I can get some help to run Norgal: 
I have uploaded the folder to our server and ran the following slurm: 

#!/bin/sh
#SBATCH --job-name=norgal
#SBATCH --account=nn9404k
#SBATCH --output=slurm-%j.base
#SBATCH --time=168:00:00
#SBATCH --nodes=1
#SBATCH --cpus-per-task=8 
#SBATCH --mem-per-cpu=3800M  
#SBATCH --partition=normal
module purge
module load python3
module load java
python /usit/abel/u1/rjsorr/norgal/norgal.py -t 8 -i /projects/bleedseq/Russell/test/CAUPYANXX_16-BLEED199_GAGATTCC-GTACTGAC_L003_R1_001_val_1.fq /projects/bleedseq/Russell/test/CAUPYANXX_16-BLEED199_GAGATTCC-GTACTGAC_L003_R2_001_val_2.fq -o /projects/bleedseq/Russell/test/norgal_output --delete --blast

have even done the same inside the norgal folder with the reads inside (python norgal.py -i CAUPYANXX_16-BLEED199_GAGATTCC-GTACTGAC_L003_R1_001_val_1.fq CAUPYANXX_16-BLEED199_GAGATTCC-GTACTGAC_L003_R2_001_val_2.fq -o norgal_output --blast), no matter what I'm getting the following error: 

python norgal.py -i CAUPYANXX_16-BLEED199_GAGATTCC-GTACTGAC_L003_R1_001_val_1.fq CAUPYANXX_16-BLEED199_GAGATTCC-GTACTGAC_L003_R2_001_val_2.fq -o norgal_output --blast
Namespace(b=10, blast=True, c=None, delete=False, e=0.0001, i=['CAUPYANXX_16-BLEED199_GAGATTCC-GTACTGAC_L003_R1_001_val_1.fq', 'CAUPYANXX_16-BLEED199_GAGATTCC-GTACTGAC_L003_R2_001_val_2.fq'], m=10000, o=['norgal_output'], r=None, t=2, trim=False)
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
0
###########
ln -s /cluster/home/rjsorr/norgal/CAUPYANXX_16-BLEED199_GAGATTCC-GTACTGAC_L003_R1_001_val_1.fq reads/trim1.fq; ln -s /cluster/home/rjsorr/norgal/CAUPYANXX_16-BLEED199_GAGATTCC-GTACTGAC_L003_R2_001_val_2.fq reads/trim2.fq
Status (0 is good): 0[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
1
Command '/cluster/home/rjsorr/norgal/binaries/linux/megahit -1 reads/trim1.fq -2 reads/trim2.fq --k-list 21,49,77,105 -t 2 -o assemblies/initial --mem-flag 0' returned non-zero exit status 126
****** Failed Assembling all reads for ND determination.. Exit.

I have also tried it with multiple versions of python...still no luck.

regards

btw: the given gitclone is not working correctly

**Comment by kosaidtu** [comment]
Hi rjsorr,

I'm thinking there's an issue with the megahit binary that comes bundled with Norgal. 

Can you please post the error from megahit, i.e.:
`tail /projects/bleedseq/Russell/test/norgal_output/log/programs.output`

Hopefully we can figure out what the problem is, and sorry for the inconvenience!

PS: Your first command should work just fine, no need to run it inside the norgal folder

**Comment by rjsorr** [comment]
thanks @kosaidtu. it looks like a permission issue. but how to fix? 

/bin/sh: /cluster/home/rjsorr/norgal_new/binaries/linux/megahit: Permission denied
The output of the different programs will be in this file.

guess the same error will occur for the other linux binaries

regards

**Comment by kosaidtu** [comment]
Try to type:
`chmod -R a+x /cluster/home/rjsorr/norgal_new/binaries/linux/`
This changes the permissions of all binaries in that folder.
Not sure if it's gonna work, but let's try!

**Comment by rjsorr** [comment]
sometimes the answer is obvious ;). had already ran a chmod and norgal has been happily running for 5 minutes. cheers and sorry for the unnecessary posting

regards

**Comment by kosaidtu** [comment]
No worries mate, good luck and thank you for trying the program :) 

(I'll leave this issue open in case other users have permission problems)

**Comment by sathudeva7** [comment]
i also have the same problem 


e15330@tesla:~/Downloads$ python norgal/norgal.py -i file_R1.fastq file_R2.fastq -o myproj --blast
Namespace(b=10, blast=True, c=None, delete=False, e=0.0001, i=['file_R1.fastq', 'file_R2.fastq'], m=10000, o=['myproj'], r=None, t=2, trim=False)
[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
0
[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
1
Command '/home/e15330/Downloads/norgal/binaries/linux/megahit -1 reads/trim1.fq -2 reads/trim2.fq --k-list 21,49,77,105 -t 2 -o assemblies/initial --mem-flag 0' returned non-zero exit status 2.
****** Failed Assembling all reads for ND determination.. Exit.

can you solve my issue
